name: Figma Token/Theme Sync
on:
  push
jobs:
  change-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup Node v18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Transform Tokens
        run: npx token-transformer ./src/theme/tokens/tokens.json ./src/theme/tokens/tokens-output.json


      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_message: "Token Transformation from Token Studio format to JSON"

