name: Sync Design Tokens

on:
  push:
    branches:    
      - '*'
      - '!main'
    paths:
      - 'src/theme/tokens/tokens.json'

jobs:

  transform:
    name: Transform tokens

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Transform tokens
      run: npx token-transformer ./src/theme/tokens/tokens.json ./src/theme/tokens/tokens-output.json

    - name: Commit changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "Updated tokens"